In [6]:
import numpy as np

In [ ]:
#Ejemplo matriz

In [2]:
matriz=np.arange(24).reshape(4,6)

In [3]:
print(matriz)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [4]:
print(matriz[2,2])

14


## Numero aleatorio

In [5]:
n=np.random.randomint(10)

AttributeError: module 'numpy.random' has no attribute 'randomint'

In [ ]:
print(n)

In [ ]:
n.np=random.choice([3,4,5,7])